### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by r41350** [justinzm/gopup#20630]
import gopup as gp
cookie==。。。 #正确的赋值后
index_df = gp.baidu_search_index(word="罩", start_date='2020-12-01', end_date='2020-12-25', cookie=cookie)
print(index_df)

报错
TypeError                                 Traceback (most recent call last)
<ipython-input-6-26bf5b18eaf8> in <module>
      2 # 怎样看cookie  https://jingyan.baidu.com/article/76a7e409284a80fc3a6e1566.html
      3 cookie =。。。 
----> 4 index_df = gp.baidu_search_index(word="罩", start_date='2020-12-01', end_date='2020-12-25', cookie=cookie)
      5 print(index_df)

C:\ProgramData\Anaconda3\lib\site-packages\gopup\index\index_baidu.py in baidu_search_index(word, start_date, end_date, cookie, type)
    264     r = requests.get(url=url, params=params, headers=headers)
    265     data = r.json()["data"]
--> 266     all_data = data["userIndexes"][0][type]["data"]
    267     uniqid = data["uniqid"]
    268     ptbk = get_ptbk(uniqid, cookie)

TypeError: string indices must be integers

**Comment by justinzm** [comment]
百度指数有调整，我迭代了一个版本，更新 0.2.9.1版本试试

**Comment by KarlChe** [comment]
update到最新版本后运行，还是会报错：
  File "D:/1/GitHub/gopup/example/test.py", line 12, in <module>
    index_df = gp.baidu_search_index(word="罩", start_date='2021-01-22', end_date='2021-01-26', cookie=cookie)
  File "d:\program files\Python\Lib\site-packages\gopup-0.2.8-py3.6.egg\gopup\index\index_baidu.py", line 266, in baidu_search_index
    all_data = data["userIndexes"][0][type]["data"]
TypeError: string indices must be integers

**Comment by justinzm** [comment]
你更新0.3.3版本试试&nbsp;

郑明
北京清博大数据科技有限公司武汉运营中心
地址：湖北省武汉市武昌区彭刘杨路232号天合大厦6楼
电话：027-87711793
手机：13377885996
邮箱：zhengming@gsdata.cn
网址：http://www.gsdata.cn
微信公号：清博 newminfo ；清博指数 indexmedia ；清博舆情web_idea；清博环保 qbhb0504



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "KarlChe"<notifications@github.com&gt;; 
发送时间: 2021年2月10日(星期三) 晚上7:44
收件人: "justinzm/gopup"<gopup@noreply.github.com&gt;; 
抄送: "justin"<3907721@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [justinzm/gopup] TypeError: string indices must be integers (#20630)





 
update到最新版本后运行，还是会报错：
 File "D:/1/GitHub/gopup/example/test.py", line 12, in 
 index_df = gp.baidu_search_index(word="罩", start_date='2021-01-22', end_date='2021-01-26', cookie=cookie)
 File "d:\program files\Python\Lib\site-packages\gopup-0.2.8-py3.6.egg\gopup\index\index_baidu.py", line 266, in baidu_search_index
 all_data = data["userIndexes"][0][type]["data"]
 TypeError: string indices must be integers
