### ISSUE TITLE
大佬帮我看看这是出什么问题了？

### ISSUE THREAD

**Issue by takashi79** [justinzm/gopup#20633]
Traceback (most recent call last):
  File "E:/pythonProject2/01.17.py", line 3, in <module>
    df_index = g.weibo_user(keyword="雷军")
  File "E:\python\lib\site-packages\gopup\pro\client.py", line 48, in query
    raise Exception(result['msg'])
Exception: 'Response' object has no attribute 'msg'

**Comment by justinzm** [comment]
微博接口反扒升级 请关注0.3.1版本 最近会更新
